### PR TITLE
Fix: The shared folder/folder id can also be a task list

### PR DESCRIPTION
**Pull request by advancingu**

### CODE REVIEW

**Comment by advancingu** [comment]
@Trim Does this look ok to you?

**Comment by Trim** [comment]
Well, I've read the thread here: Ericsson/exchangecalendar#461 and I doesn't understand when the issue occurs and what this commit fixes.

@Pro says:

> Your EWS plugin allows to add shared folders by indicating the EWS ID of that folder. E.g. another user can share his calendar with me. To add the calendar to Thunderbird I use the ID of the folder to add it.

But I don't know where is this option / dialog ? Does Outlook send a mail with a sharing invite ?
Where can I "use the ID of the folder to add it" ?

As I can't find that, I suggest to wait for more details from @Pro

Furthermore, there's a dialog which can view and add shared calendar / tasks lists:
If you right click on calendar you can open a dialog named "Delegate Calendar" and there you can find shared calendars by other users. If you open this dialog from a calendar containing task list, it will show you shared task lists.

**Comment by Pro** [comment]
@Trim the commit allows to add a subfolder task list from another user into Thunderbird/lightning.

E.g. User1 can create a specific task list, let's say "Shopping" as a subfolder in his main task list.
When User1 shares the Shopping list with User2 within Outlook, User2 gets an E-Mail and he can accept the invitation within Outlook.

To add this task list to thunderbird, you need the EWS ID of that list.
(I wrote some C# code to get the correct ID from that invitation email). After you have the ID, currently the plugin fails because it is not a shared calendar, but a shared task list.
Using the commit, this problem is solved and you can easily add the list. And yes, it's really as simple as just accepting the `IPF.Task` type.

I think (not tested) that the dialog you mentioned above is only able to find the main task list of a user, and not a subfolder of the task list. Maybe this needs further investigation...

**Comment by advancingu** [comment]
I'm merging this for now since the risk of breaking a lot of things appears low. In case this causes any new bugs, those can be raised as new issues.

**Pull request merged**
