### PR TITLE
#277 Compatibility with Thunderbird 67 and newer versions

### PR DESCRIPTION
**Pull request by advancingu**

### CODE REVIEW

**Comment by jan-kiszka** [comment]
How should that alone work? To my understanding, TB 68 dropped the classic overlay hooks via chrome.manifest.

**Comment by pablaasmo** [comment]
I have compiled and installed this version, but do not seem to get it to work properly.
It no longer claims it to be a legacy extension, but I am not able to add an Exchange Calendar.
image

I though I should see a choice for an exchange calendar in this windows?
Or am I wrong*

**Comment by jan-kiszka** [comment]
I'm currently re-animating the Toggle Word Wrap addon because it's essential for my workflows. Seems that ```"legacy": true``` in manifast.json can reactivate thinks to a good degree. I just had to change one interface name. Anyway, this "legacy" tag is missing in that PR. Will try adding that later.

The bad news is this, though: https://developer.thunderbird.net/add-ons/tb78

**Comment by jan-kiszka** [comment]
Made "progress" with this patch:
```
diff --git a/manifest.json b/manifest.json
index 4b5ed94..1697fc3 100644
--- a/manifest.json
+++ b/manifest.json
@@ -9,10 +9,10 @@
   "name": "Exchange Calendar",
   "description": "Synchronize calendars, tasks, and contacts with Microsoft Exchange.",
   "version": "5.0.0.2",
-  "version_name": "5.0.0-beta2",
   "icons": {
     "32": "common/theme/common/images/lightningexchangecalendar.png"
   },
   "homepage_url": "https://github.com/ExchangeCalendar/exchangecalendar",
-  "author": "ExchangeCalendar community"
+  "author": "ExchangeCalendar community",
+  "legacy": true
 }
```

This is the progress, shown during TB startup:
```
[Exception... "ComponentManager::CreateInstance returned failure code:"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: resource://calendar/calendar-js/calCalendarManager.js :: createCalendar :: line 442"  data: no]
```
There is more in the logs. I've no idea what all that means.

**Comment by pablaasmo** [comment]
Are we allowed to push commits to this branch, or is that restricted to the branch creator?

**Comment by advancingu** [comment]
@pablaasmo Create a Pull Request from your clone against this branch.

**Comment by killerbot242** [comment]
when will a new beta be created with support for the TB 67 and above ? Really missing the broken plug-in ...

**Comment by saif-ellafi** [comment]
Looking forward to this! any estimate for a release?

**Comment by abelal** [comment]
Any news here?

**Comment by denim2x** [comment]
Working on it

**Comment by oscar-rr** [comment]
> 
> 
> Working on it

any news here ?

**Comment by chriswells0** [comment]
TbSync works with current Thunderbird versions if anyone needs an interim solution:

https://addons.thunderbird.net/en-US/thunderbird/addon/tbsync/

**Comment by advancingu** [comment]
Archiving this project.

**Pull request closed without merging**
