### PR TITLE
Fix timezone display in calendar view

### PR DESCRIPTION
**Pull request by Trim**
The exchange calendar cache uses the UTC timezone and the given range to filter is in local timezone.

The code has been automatically beautified to be able to work on it.

On functions I had to read, I simplified the code to have less conditions and use better local variables.

### CODE REVIEW

**Comment by Trim** [comment]
Ah, I've just seen same error inside the `getItemsFromOfflineCache`, please wait before merging.

**Comment by Trim** [comment]
Ok, I've updated the code, but I wasn't able to work in offline mode (even with the 4.0.0-beta4 release).

Maybe offline mode is just not working ?

**Comment by advancingu** [comment]
First of all, thanks for attacking this big mess of a file. Unfortunately it is _really_ hard to tell what you actually changed semantically since you changed all the formatting as well, even with whitespace ignore mode on Github. Next time, please try to apply the formatting in a separate PR first, then it is much easier to review and comment on the changes. Right now, I will simply do a test run once I have time and approve as long as it doesn't fail, however I will not have reviewed the code in detail.

Regarding offline mode, I have no idea whether or not it works.

**Comment by Trim** [comment]
Well, if you look history commits by commits, you'll see that the fix is this one: https://github.com/ExchangeCalendar/exchangecalendar/commit/93e6c600055f91c221edd44780d6ce84e3de4b6b

I can do three PRs for : 
1. Auto formating
2. Code cleaning (remove unused parts)
3. Bug fixing

I'll do that this morning, tanks for the comment :)

**Pull request closed without merging**
