### PR TITLE
Fix timezone display part 2 / 5

### PR DESCRIPTION
**Pull request by Trim**
Code cleanup in mivExchangeCalendar.js / getItems

### CODE REVIEW

**Comment by advancingu** [comment]
You will now have to merge `ec-4.0` into your branch here for the formatting changes to go away, otherwise I'd be reviewing them twice.

**Comment by Trim** [comment]
I've just updated the branch. That's so a pain to send multi part pull request on Github :/

**Comment by advancingu** [comment]
I think it might have to do with how you created your branches. Did you branch the second from the first, third from second, etc.? If not, that would explain why Github didn't understand that the first branch's changes were already included when I looked at the original diff of the second branch here.

**Comment by Trim** [comment]
I've simply made three branches directly from commits of the original branch (commits are exactly the same). I think the issue comes from the merge commit added by Github each time a pull request is merged.

**Comment by advancingu** [comment]
No, the issue appears to be different from what you describe. What I believe you did is commit identical content to each branch separately, however since these commits were all done at different times, the commit hashes are all different. That way Github or any other git tool will consider them non-equal commits.

What you can do instead is create your first branch, do all the first changes in there, then commit and push. Then create the second branch off the last commit of the first branch, do your changes, then commit and push. And so on. This way all subsequent branches will contain the _exact same_ commits as the previous branches and not just _equivalent_ commits (of course there are very likely several other ways to do this, too).

**Comment by Trim** [comment]
Mmh, part 4 and 5 wasn't using same remote as pull request origin. I've just fixed that and it seems now that every pull request have same git history (comparing first characters of each commit hash).

**Comment by advancingu** [comment]
:+1: Ok, I'll look at it later.

**Comment by advancingu** [comment]
I don't see any apparent issues. :+1: Thanks!

**Pull request merged**
