### PR TITLE
First steps towards making it work for thunderbird 60

### PR DESCRIPTION
**Pull request by llange**
Standing on the shoulders of ~~giants~~@Trim I was able to add the necessary changes so that the extension is now "working for me" in thunderbird 60 and able to retrieve existing calendar, or create new calendars.
So far, it looks good (but I only did simple usage and only a few hours, and have only one important calendar to sync), and the open issues are : 
* `The use of Mutation Event is obsolete. Use MutationObserver instead.  calendar-widgets.xml:512:20`
* I was forced to remove a startBatch / endBatch pair. Cf the FIXME in llange/exchangecalendar@0ef8365a6c1183a8e9fcd14eac5f27fcf81d9dde
* I couldn't maintain initial loading of XML timezone file (present in the extension), cf llange/exchangecalendar@60173b9a68d7e62dfb914d667df345b8eaf2bbba

Also I added a fix for an issue with the SOAP message generation which was preventing me to test calendar creation. I don't know if it's related to thunderbird 60, or if the issue was existing previously (could not test it), cf llange/exchangecalendar@d749a1b99dbf15218a1ed7b4d7de6f07d671d349

I think now it's time that more people have a look a it (and bear with my ignorance of the (exchange/lightning) calendar context, thunderbird addons and ES6) and see if it can be a first step towards resolution of #178

### CODE REVIEW

**Comment by jhenkehd** [comment]
I have build and tested this PR, but it does not sync any of calendar, tasks or contacts. The only thing that happens is, that there are constantly 6 background tasks running.

**Comment by actionfoggi** [comment]
Same behavior here. No sync, but constantly running background tasks.

**Comment by llange** [comment]
Thanks for the report.

I did have it sometimes, and usually it was because it was triggering one part of the code that was still incorrect (pre-tb 60 javascript constructs, or services not existing anymore).

Let's find this.

Can you please do the following tests ?
* If possible, disable all your extensions (except lightning + exchangecalendar) and restart
* While the background tasks are running, open the console (Tools -> Dev Tools -> Error console ; or use the shortcut). The first time, please disable all the logs except: CSS/Errors, JS/Errors, JS/Warnings, Security/Errors, Security/Warnings, Log/Errors, Log/Warnings, Log/SharedWorkers, Log/ServiceWorkers, Log/ModuleChromeWorkers, Server/Errors, Server/Warnings
* Check if any errors appearing in the logs relate to this module, and send me the corresponding message / file / line please.

Also, please provide me with TB Version, Lightning Version and O/S so that I see if there is any impact of these.

Regards,

**Comment by jhenkehd** [comment]
```
DebuggeeWouldRun: debuggee `resource://devtools/shared/base-loader.js:428' would run  builtin-modules.js:185:11
Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen.  calendar-widgets.xml:512:20
TypeError: setting getter-only property "userPass"[Weitere Informationen]  mivExchangeAuthPrompt2.js:352:86
DebuggeeWouldRun: debuggee `resource://devtools/shared/base-loader.js:428' would run  builtin-modules.js:185:11
2018-08-16 12:28:11	autosyncActivities	ERROR	onDownloadCompleted: TypeError: this._syncInfoPerFolder.get(...) is undefined
  log4moz.js:680
TypeError: this._syncInfoPerFolder.get(...) is undefined[Weitere Informationen]
```
Thunderbird 60.0, Lightning 6.2, Linux

**Comment by actionfoggi** [comment]
``
TypeError: setting getter-only property "userPass"[Weitere Informationen]  mivExchangeAuthPrompt2.js:352:86
TypeError: this.chromeUtilsWindow.openUILinkIn is not a function[Weitere Informationen]  hudservice.js:387:7
``

TB 60, Lightning 6.2, Ubuntu 16.04

**Comment by llange** [comment]
Thanks. Both of you are hit by the same issue:
`TypeError: setting getter-only property "userPass"[Weitere Informationen] mivExchangeAuthPrompt2.js:352:86`

I'm having a look at it.

**Comment by llange** [comment]
As I cannot test this, could you please check if it unblocks you ? Otherwise I'll need to add some logging, try to reproduce, etc...
By the way, this seems to be triggered by and issue with the login and/or password.
Did you set the login / password to your Exchange server in the saved passwords ? Did you change it lately ? Any way to test if it is ok or not ?

Also: did you create a new calendar, or is it your pre-tb60 calendar ?

**Comment by actionfoggi** [comment]
same behavior and same error message with your latest commit. 
Yes the login / password is in the saved passwords. I didn't have changed it lately and it is a pre-TB60 calendar. 
But, if i try to create e new calendar via auto-discovery, I have to enter the password and then the dialogs never finishes. The same error as before is shown in the console.

**Comment by llange** [comment]
Try again ? I removed the offending code, let's see where this breaks.

**Comment by jhenkehd** [comment]
Still same symptoms. No sync, just background processes running.

**Comment by llange** [comment]
@jhenkehd , is this with the last commit bd89d1b ?
Can you give me the error/warnings related to this test please ?

**Comment by jhenkehd** [comment]
Yes, commit bd89d1bd39ce331e1d5e184de5e03692738c7b54.

I have some appointments now, probably @actionfoggi can provide more debugging. It would be very useful to have it working in TB60 ASAP.

**Comment by actionfoggi** [comment]
Background jobs are running now. but curiously I get a partial sync, only a few evens get synced.
No error message in the console. 

I've to leave the the office now. I'll will have a closer look on this one tomorrow. Thanks so far!

**Comment by actionfoggi** [comment]
Today morning I opend TB60 and the sync is still pending (pre-TB60 calendar). Also there are no error messages in the console. 
I tried to added a new calendar via auto-discovery (this time it worked), but still no sync and no error messages.

**Comment by llange** [comment]
please start thunderbird from the console, in a terminal, and check the stdout/stderr.
Reproduce your issue.
Then quit thunderbird (important : it adds more log).
You should be able to see some (or a lot, depending on your extensions...) of lines starting with "JavaScript error: ....".
In those lines, search for lines having "miv" or "exchange" in them (case insensitive).
You'll also find (near end of console) the same error, but this time reported with file/line (this is important), like : 
`JavaScript error: jar:file://XXXXXXXXXXXXXXXXX/extensions/exchangecalendar@extensions.1st-setup.nl.xpi!/calendar/interface/exchangeCalendar/mivExchangeCalendar.js, line 10897: ReferenceError: getCalendarManager is not defined`
Then report all of them - they most likely are an indication of an error.

I just added another fix to this branch. It may (or may not) make some progress.

Sorry for the step by step approach, I need to reproduce the issue here first, and the behaviour is not the same at each launch - it seems we are taking different paths of the code at each launch, so the errors are not appearing every time.

**Comment by actionfoggi** [comment]
Okay I ended up removing the add-on and added it again.
Then I added a completely new calendar. I few events got synced, but not all. 

Thats the log output from the console:
`[calBackendLoader] Using Thunderbird's builtin libical backend
JavaScript strict warning: resource://gre/modules/TelemetryEnvironment.jsm, line 734: ReferenceError: reference to undefined property "isActive"
JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 159: ReferenceError: reference to undefined property "additionalBackgrounds"
JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 206: ReferenceError: reference to undefined property "popup"
JavaScript strict warning: resource://gre/modules/ProfileAge.jsm, line 201: ReferenceError: reference to undefined property "reset"
JavaScript strict warning: jar:file://XXXXXXXX/Applications/thunderbird/omni.ja!/components/mozIntl.js, line 83: ReferenceError: reference to undefined property "timeStyle"
progress_panel

erSyncFolderItemsRequest.onSendOk: try error 'TypeError: tasks is undefined'.
JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 4947: ReferenceError: reference to undefined property "signedState"
JavaScript strict warning: chrome://calendar/content/widgets/calendar-list-tree.xml, line 668: ReferenceError: reference to undefined property 0
JavaScript strict warning: chrome://messenger/content/mail-compacttheme.js, line 66: TypeError: setting getter-only property "styleSheet"
1534496011557	addons.xpi-utils	WARN	Error: XPI database modified after shutdown began (resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:323:17) JS Stack trace: saveChanges@XPIProviderUtils.js:323:17
updateActiveAddons@XPIProviderUtils.js:1070:9
shutdown@XPIProvider.jsm:2379:7
_startProvider/AMProviderShutdown/<@AddonManager.jsm:743:21
AMProviderShutdown@AddonManager.jsm:741:16
trigger@AsyncShutdown.jsm:710:23
_wait@AsyncShutdown.jsm:857:7
wait@AsyncShutdown.jsm:841:28
shutdownManager@AddonManager.jsm:1114:15
trigger@AsyncShutdown.jsm:710:23
_wait@AsyncShutdown.jsm:857:7
wait@AsyncShutdown.jsm:841:28
observe@AsyncShutdown.jsm:524:17
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 5087: ReferenceError: reference to undefined property "applySoftBlock"
[calBackendLoader] Using Thunderbird's builtin libical backend
JavaScript strict warning: resource://gre/modules/ProfileAge.jsm, line 201: ReferenceError: reference to undefined property "reset"
JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 159: ReferenceError: reference to undefined property "additionalBackgrounds"
JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 206: ReferenceError: reference to undefined property "popup"
JavaScript strict warning: jar:file://XXXXXXXX/Applications/thunderbird/omni.ja!/components/mozIntl.js, line 83: ReferenceError: reference to undefined property "timeStyle"
JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 4947: ReferenceError: reference to undefined property "signedState"
JavaScript strict warning: resource://gre/modules/addons/XPIInstall.jsm, line 2555: ReferenceError: reference to undefined property 32
JavaScript strict warning: chrome://mozapps/content/extensions/extensions.js, line 2643: ReferenceError: reference to undefined property "mInstall"
JavaScript strict warning: chrome://messenger/content/mail-compacttheme.js, line 66: TypeError: setting getter-only property "styleSheet"
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 5087: ReferenceError: reference to undefined property "applySoftBlock"
JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 6250: ReferenceError: reference to undefined property "action"
[calBackendLoader] Using Thunderbird's builtin libical backend
JavaScript strict warning: resource://gre/modules/ProfileAge.jsm, line 201: ReferenceError: reference to undefined property "reset"
JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 159: ReferenceError: reference to undefined property "additionalBackgrounds"
JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 206: ReferenceError: reference to undefined property "popup"
JavaScript strict warning: jar:file://XXXXXXXX/Applications/thunderbird/omni.ja!/components/mozIntl.js, line 83: ReferenceError: reference to undefined property "timeStyle"
progress_panel
JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 4947: ReferenceError: reference to undefined property "signedState"
calICalendarACLEntry getOwnerIdentities:null
dcbcdcb6-acdf-4a88-9674-978ba03034e2:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
d3655440-1b08-488b-86c8-5e7b47a0a62b:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
0f757a6d-9446-4a7e-84f9-22bcd7a40fc5:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
98ec55d4-bfa5-4a69-a652-a0b091c87b41:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
322b7703-dd4a-468e-8b6d-d1d184ea8d1f:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
e50285e1-a3fa-4850-ad6f-dc8d52cc75d4:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
10a542f6-26e1-4fb2-b646-cb5280bdb405:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
fd784b96-ef8e-493c-9a49-4baf435a42bc:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
c7229689-ae1b-4eaf-9bc6-ffbc10675df2:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
JavaScript strict warning: resource://exchangecommoninterfaces/exchangeBaseItem/mivExchangeBaseItem.js, line 1865: ReferenceError: reference to undefined property "getScriptableHelper"
77b84c24-ebd3-4730-aa37-1f41d0ddf034:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
72b8eee1-feb2-411c-be11-a663aad13fec:https://XXXXXXXX/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: aList is not iterable
JavaScript strict warning: chrome://messenger/content/mail-compacttheme.js, line 66: TypeError: setting getter-only property "styleSheet"`

Hope that helps...

**Comment by llange** [comment]
Thanks.
Can you please confirm that you indeed have this line in your stdout:
`JavaScript strict warning: resource://exchangecommoninterfaces/exchangeBaseItem/mivExchangeBaseItem.js, line 1865: ReferenceError: reference to undefined property "getScriptableHelper"` ?
I cannot find a call to `getScriptableHelper` in this line... strange.
And just in case, please confirm you did compile the latest version and installed that one.

**Comment by llange** [comment]
I fear we may have lots of similar errors. It seems they're related to a javascript engine change ([for each support removed](https://www.fxsitecompat.com/en-CA/docs/2017/for-each-in-loop-support-has-been-removed/)), and the [replacement syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/For-each-in_loops_are_deprecated) is not straightforward, as we need to handle the case of the object being (or not) an array, being nullable, etc...

Unfortunately I fear that I'm doing it wrong, as I do not know the code nor the type of the objects.

However I did a quick fix for your issue here, but the real way to do it would be to audit all the (previous) `for each....`, and make a replacement depending on the object type. Huge work.

**Comment by actionfoggi** [comment]
I see.... 
Adding a new calendar syncs know every event, but if I close and reopen TB60 all events are gone and the sync is pending like before.

Looks like there will be no easy fix.

**Comment by llange** [comment]
As this patchset becomes too complex to correct, I restarted from ec-4.0 it in another branch and did (what I think is) the proper replacement for the `for each(...)`syntax.

It still works for me (even better), and I think it may also work better for @jhenkehd and @actionfoggi.

The pull request is #189 and the branch is [llange:thunderbird-60-2nd-try](/llange/exchangecalendar/tree/thunderbird-60-2nd-try), please have a look and try it, i'll be closing this PR (and the corresponding branch) if everything is fine.

**Comment by llange** [comment]
Use #189

**Pull request closed without merging**
