### PR TITLE
correct Makefile for install.rdf.template

### PR DESCRIPTION
**Pull request by Mechtilde**
My PR for #159

### CODE REVIEW

**Comment by Mechtilde** [comment]
Hello,
Am 11.02.2018 um 20:17 schrieb Adrien Dorsaz:
> Trim requested changes on this pull request.
> 
> If I understamd correctly, `install.rdf` is a make target and should be kept here.
> 
> I think we should add it to the `.PHONY` line to be sure it's correctly understood by make as a target.
> 

I did only an offer. You know the code and what should be done

Mechtilde

-- 
Mechtilde Stehmann
## Apache OpenOffice
## Freie Office Suite für Linux, MacOSX, Windows
## Debian Developer
## Loook, calender-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by Trim** [comment]
Sorry if it was harshed, I didn't want to be rude. I don't know exactly how the current Makefile works, has it has been updated by another PR recently.

Furthermore, I personally didn't have any issues with building on Debian.

Due to this context, I was only able to give you some advice (by using "should"), as I don't know exactly the code and I didn't had this issue.

Does the updated version now works for you ?

**Comment by Mechtilde** [comment]
Hello Adrien,
helo all,

Am 13.02.2018 um 08:23 schrieb Adrien Dorsaz:
> Sorry if it was harshed, I didn't want to be rude. I don't know exactly how the current Makefile works, has it has been updated by another PR recently.

You was the person who deleted the file <build.sh> and created the file
<MAKEFILE> on 2017-09.22.

Eugene M. Kim did the change from <install.rdf> to <install.rdf.template
on 2018-01-26.

> Furthermore, I personally didn't have any issues with building on Debian.

Building *on* Debinan isn't the same as building *for* Debian. Can you
send me your file <rules> so I can compare it.
> 
> Due to this context, I was only able to give you some advice (by using "should"), as I don't know exactly the code and I didn't had this issue.

I can't change it on my own. I had too less knowlegde about the side
effects this can have.

Kind regards

Mechtilde


-- 
Mechtilde Stehmann
## Apache OpenOffice
## Freie Office Suite für Linux, MacOSX, Windows
## Debian Developer
## Loook, calender-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by Trim** [comment]
As there was a misunderstanding about the error we try to fix, I'm closing this PR: as noticed in the report #159 the issue doesn't come from the Makefile, but from the Debian specific `install-xpi` instruction which is looking for the `install.rdf` file.

**Pull request closed without merging**
