### PR TITLE
Finish code tree building, fix password in dialogs, merge macOS build fixes

### PR DESCRIPTION
**Pull request by Trim**
Finally, I took times to rebuild the code tree according to issue #80 

While doing tests, I think I've found a workaround for issues like #103 

I've took also the opportunity to merge and test directly PR #142 to fix build on macOS and create always new file archive (thanks to @astralblue).

Sorry for that such big PRs, I hope it will be the last huge PR to move and modify enverything in the repo :/

PS: These PRs are merged too with this pull request: #142 #135 #133 #122 #120 #119

### CODE REVIEW

**Comment by advancingu** [comment]
> +56,401 −60,888
😱 
This should be interesting to review.

**Comment by advancingu** [comment]
Ok, I looked through the structure and it appears to be in _much_ better shape than before. Thanks a lot for all your work!

Unfortunately I don't have the time to check if the code still works (too bad there aren't any tests), so merging will be on good faith basis once again. However, with one more beta release there should be opportunity to catch obvious regressions.

**Comment by advancingu** [comment]
@Trim Would you be able to update the CHANGELOG file with all the PRs that have been merged since beta4? Also, there are some new locales that were added on Transifex that might still need integration. Since those only have 0% translated, I'm not sure what the process is there.

I'll try to get a new beta release out once things are ready.

**Comment by Trim** [comment]
Cool, thanks for the merge 👍 
Indeed, I find too the code a bit more comprehensive with this structure.

Yes, I'm updating the CHANGELOG and I'll push and get new translations from Transifex.

**Pull request merged**
