### PR TITLE
Event dialog: fix content editor and attendees dialog

### PR DESCRIPTION
**Pull request by Trim**
This merge request try to resolve issue #5 and the "add attendees dialog":

- Update the dialog overlay to current Thunderbird/Lightning dialog (lot of the overlay were moved from calendar-event-dialog.xul to lightning-item-iframe.xul to reflect the current window structure)
- Remove the override of edit attendees and let Lightning manage that
- Update the way the dialog initialize the HTML content editor (for Exchange Tasks) by using DOM to parse and set correct HTML code in the content

Some times, the HTML editor won't work: you'll be unable to see/edit content and toolbar buttons will be not responding. When the editor is in this state, a workaround is to close the window and open it again.

### CODE REVIEW

**Comment by advancingu** [comment]
@Trim Thanks as well for the PR here.

Tested a bit and found the following:

In this PR, date and time input boxes are double-nested:
screenshot from 2017-06-07 21-12-38

In the `ec-4.0` branch they look like this (correct):
screenshot from 2017-06-07 21-15-45

**Comment by Trim** [comment]
Thanks for the tests, I supposed that was because of the GTK3 migration of Thunderbrid, so I didn't take care. I'll check why we have such double nest.

**Comment by Trim** [comment]
Well, this commit fix the double nesting for the current TB release.

Although, for the current TB beta, it looses the new graphical datetime picker.

I'm looking to find a solution to have both working, but for now, this code works with TB release.

**Comment by Trim** [comment]
I'll made a new branch to fix the entire event-dialog.

On this one, I've made a lot of experiments and they are more noise than really relevant.

I have to take time to read [this documentation](https://wiki.mozilla.org/Calendar:Event_in_a_Tab/documentation) and make a plan before coding.

**Comment by Trim** [comment]
Ok, Lightning allows now to use window dialog or tabs to open event and tasks.

That's why the dialog is now defined in an iframe.

First step for us will be to correctly update the standard window dialog, then we could take in consideration for the tab view.

I didn't now, but the parent can modify its ifram child by use of contextWindow: https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow

So, we should be able to use work in this branch.

**Comment by advancingu** [comment]
Great, that sounds like it will do the trick.

**Comment by Trim** [comment]
Ok, I've updated this branch as the work wasn't so big I thought yesterday.

Now attachment menus and attachment list works well (including context menu on right click).

I think I won't have the motivation to debug the issue with the HTML content editor.
But I can add a screen cast to display what happens some times: [video illustrating the issue](https://cloud.adorsaz.ch/index.php/s/1ro5UXLuxLDrVrd/download)

**Comment by advancingu** [comment]
@Trim Great, this works fine now.

**Pull request merged**
